-- Development-only owner. Never apply this seed to production.
insert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at,confirmation_token,recovery_token,email_change_token_new,email_change)
values ('00000000-0000-0000-0000-000000000000','d0000000-0000-0000-0000-000000000001','authenticated','authenticated','demo-owner@localhost.invalid','',now(),'{"provider":"email","providers":["email"]}','{"first_name":"Utente","last_name":"Demo","accepted_terms":true}',now(),now(),'','','','') on conflict (id) do nothing;
insert into public.tournaments(owner_id,name,public_title,tournament_date,start_time,end_time,public_slug) values ('d0000000-0000-0000-0000-000000000001','Torneo demo Baraonda','Baraonda Padel Demo','2026-09-20','10:00','19:00','demo-baraonda') on conflict do nothing;
insert into public.tournament_breaks(tournament_id,title,starts_at,ends_at) select id,'Pausa pranzo','2026-09-20 13:00+00','2026-09-20 14:00+00' from public.tournaments where public_slug='demo-baraonda' on conflict do nothing;
insert into public.players(tournament_id,first_name,last_name,level,gender,sort_order) select t.id,'Giocatore ' || n,'Demo',case when n <= 6 then 'advanced' when n <= 13 then 'intermediate' else 'beginner' end,case when n % 3 = 0 then 'female' else 'male' end,n from public.tournaments t cross join generate_series(1,19) n where t.public_slug='demo-baraonda' on conflict do nothing;
insert into public.player_availability(player_id,available_from,available_until) select p.id,'2026-09-20 10:00+00','2026-09-20 16:00+00' from public.players p join public.tournaments t on t.id=p.tournament_id where t.public_slug='demo-baraonda' and p.sort_order in (1,2,3) on conflict do nothing;
insert into public.player_constraints(tournament_id,player_a_id,player_b_id) select t.id,a.id,b.id from public.tournaments t join public.players a on a.tournament_id=t.id and a.sort_order=1 join public.players b on b.tournament_id=t.id and b.sort_order=2 where t.public_slug='demo-baraonda' on conflict do nothing;
insert into public.matches(tournament_id,sequence_number,starts_at,ends_at,team_a_player_1_id,team_a_player_2_id,team_b_player_1_id,team_b_player_2_id,team_a_games,team_b_games,status) select t.id,1,'2026-09-20 10:00+00','2026-09-20 10:15+00',p1.id,p2.id,p3.id,p4.id,6,4,'completed' from public.tournaments t join public.players p1 on p1.tournament_id=t.id and p1.sort_order=1 join public.players p2 on p2.tournament_id=t.id and p2.sort_order=3 join public.players p3 on p3.tournament_id=t.id and p3.sort_order=4 join public.players p4 on p4.tournament_id=t.id and p4.sort_order=6 where t.public_slug='demo-baraonda' on conflict (tournament_id,sequence_number) do nothing;
insert into public.matches(tournament_id,sequence_number,starts_at,ends_at,team_a_player_1_id,team_a_player_2_id,team_b_player_1_id,team_b_player_2_id,status) select t.id,2,'2026-09-20 10:15+00','2026-09-20 10:30+00',p1.id,p2.id,p3.id,p4.id,'scheduled' from public.tournaments t join public.players p1 on p1.tournament_id=t.id and p1.sort_order=5 join public.players p2 on p2.tournament_id=t.id and p2.sort_order=7 join public.players p3 on p3.tournament_id=t.id and p3.sort_order=8 join public.players p4 on p4.tournament_id=t.id and p4.sort_order=9 where t.public_slug='demo-baraonda' on conflict (tournament_id,sequence_number) do nothing;
