import { type FormEvent, useEffect, useState } from 'react';
import { useAuth } from '../../auth/useAuth';
import { AuthShell, navigate } from '../auth/AuthPages';

export function ProfilePage() {
  const { user, profile, updateProfile } = useAuth(); const [firstName, setFirstName] = useState(profile?.firstName ?? ''); const [lastName, setLastName] = useState(profile?.lastName ?? ''); const [marketingConsent, setMarketingConsent] = useState(profile?.marketingConsent ?? false); const [error, setError] = useState<string | null>(null); const [saved, setSaved] = useState(false); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { if (profile) { setFirstName(profile.firstName); setLastName(profile.lastName); setMarketingConsent(profile.marketingConsent); } }, [profile]);
  const submit = async (event: FormEvent) => { event.preventDefault(); const first = firstName.trim(); const last = lastName.trim(); if (first.length < 2 || first.length > 80) return setError('Il nome deve contenere da 2 a 80 caratteri.'); if (last.length < 2 || last.length > 80) return setError('Il cognome deve contenere da 2 a 80 caratteri.'); setSubmitting(true); setSaved(false); setError(null); try { await updateProfile({ firstName: first, lastName: last, marketingConsent }); setSaved(true); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Non è stato possibile aggiornare il profilo.'); } finally { setSubmitting(false); } };
  return <AuthShell title="Il tuo profilo" wide><form onSubmit={submit} noValidate><div className="profile-facts"><span>Email<strong>{user?.email}</strong></span><span>Registrazione<strong>{profile?.createdAt ? new Intl.DateTimeFormat('it-IT', { dateStyle: 'long' }).format(new Date(profile.createdAt)) : '—'}</strong></span><span>Conferma email<strong>{user?.email_confirmed_at ? 'Confermata' : 'In attesa'}</strong></span></div><div className="auth-form-grid"><label>Nome<input value={firstName} onChange={event => setFirstName(event.target.value)} maxLength={80} /></label><label>Cognome<input value={lastName} onChange={event => setLastName(event.target.value)} maxLength={80} /></label></div><label className="auth-checkbox"><input type="checkbox" checked={marketingConsent} onChange={event => setMarketingConsent(event.target.checked)} /><span>Desidero ricevere aggiornamenti sul servizio.</span></label>{saved && <p className="auth-success" role="status">Profilo aggiornato.</p>}<p className="auth-error" role="alert">{error}</p><button className="auth-submit" disabled={submitting}>{submitting ? 'Salvataggio…' : 'Salva modifiche'}</button><button className="auth-link" type="button" onClick={() => navigate('/tournaments')}>Torna ai tornei</button></form></AuthShell>;
}
