import { Plus, Trash2 } from 'lucide-react';
import { Gender, Level, Player, PlayerStatus, Tournament, uid } from '../models';

export function Players({ tournament, update }: { tournament: Tournament; update: (fn: (t: Tournament) => Tournament) => void }) {
  const add = () => update(t => ({ ...t, players: [...t.players, { id: uid(), firstName: 'Nuovo', lastName: 'Giocatore', level: 'Intermedio', gender: 'Uomo', notes: '', availability: [{ from: t.settings.start, to: t.settings.end }], avoidPartners: [], status: 'attivo' }] }));
  const patch = (id: string, changes: Partial<Player>) => update(t => ({ ...t, players: t.players.map(player => player.id === id ? { ...player, ...changes } : player) }));
  return <><header><div><h1>Giocatori</h1><p>Disponibilità, livello, genere e incompatibilità di coppia.</p></div><button onClick={add}><Plus size={17} /> Aggiungi</button></header><div className="player-list">{tournament.players.map(player => <div className="player" key={player.id}>{/* Text fields are uncontrolled (defaultValue + onBlur) so typing never touches global
        state; value-based keys remount them when the underlying value really changes
        (e.g. a sync from another device), keeping the DOM from showing stale data. */}
      <div className="grid"><input aria-label="Nome" key={`first-${player.firstName}`} defaultValue={player.firstName} onBlur={e => patch(player.id, { firstName: e.target.value })} /><input aria-label="Cognome" key={`last-${player.lastName}`} defaultValue={player.lastName} onBlur={e => patch(player.id, { lastName: e.target.value })} /><select value={player.level} onChange={e => patch(player.id, { level: e.target.value as Level })}><option>Principiante</option><option>Intermedio</option><option>Avanzato</option></select><select value={player.gender} onChange={e => patch(player.id, { gender: e.target.value as Gender })}><option>Uomo</option><option>Donna</option><option>Altro</option></select><select value={player.status} onChange={e => patch(player.id, { status: e.target.value as PlayerStatus })}><option value="attivo">Attivo</option><option value="ritardo">In ritardo</option><option value="assente">Assente</option><option value="infortunato">Infortunato</option><option value="ritirato">Ritirato</option></select><button className="danger" aria-label="Elimina giocatore" onClick={() => update(t => ({ ...t, players: t.players.filter(p => p.id !== player.id), matches: t.matches.filter(m => !m.players.includes(player.id)) }))}><Trash2 size={16} /></button></div><textarea placeholder="Note" key={`notes-${player.notes}`} defaultValue={player.notes} onBlur={e => patch(player.id, { notes: e.target.value })} /><div className="sub"><b>Disponibilità</b>{player.availability.map((availability, i) => <span key={i}><input type="time" key={`from-${availability.from}`} defaultValue={availability.from} onBlur={e => patch(player.id, { availability: player.availability.map((item, j) => j === i ? { ...item, from: e.target.value } : item) })} /><input type="time" key={`to-${availability.to}`} defaultValue={availability.to} onBlur={e => patch(player.id, { availability: player.availability.map((item, j) => j === i ? { ...item, to: e.target.value } : item) })} /><button onClick={() => patch(player.id, { availability: player.availability.filter((_, j) => j !== i) })}>×</button></span>)}<button className="small" onClick={() => patch(player.id, { availability: [...player.availability, { from: tournament.settings.start, to: tournament.settings.end }] })}>+ fascia</button></div><div className="sub"><b>Non può essere compagno di</b><select multiple value={player.avoidPartners} onChange={e => patch(player.id, { avoidPartners: Array.from(e.target.selectedOptions).map(option => option.value) })}>{tournament.players.filter(other => other.id !== player.id).map(other => <option key={other.id} value={other.id}>{other.firstName} {other.lastName}</option>)}</select></div></div>)}</div></>;
}
