import { Lock, Shuffle, Undo2, Unlock } from 'lucide-react';
import { useState } from 'react';
import { Match, Tournament, fullName } from '../models';
import { generateSchedule } from '../solver';
import { MATCH_BALANCE_LABELS, calculateMatchBalance, isBalanceWarning } from '../services/matchBalance';

export function Schedule({ tournament, update }: { tournament: Tournament; update: (fn: (t: Tournament) => Tournament) => void }) {
  const names = new Map(tournament.players.map(player => [player.id, fullName(player)]));
  const [dragged, setDragged] = useState<{ matchId: string; position: number }>();
  const regenerate = () => update(t => ({ ...t, previousMatches: t.matches, matches: generateSchedule(t, true) }));
  const changePlayers = (match: Match, players: Match['players']) => {
    const rating = calculateMatchBalance({ ...match, players }, tournament.players);
    if (rating.score < 40 && !window.confirm(`Questa modifica genera una partita molto sbilanciata (${rating.score}/100).\nVuoi continuare?`)) return;
    update(t => ({ ...t, matches: t.matches.map(item => item.id === match.id ? { ...item, players, violations: [...item.violations.filter(warning => !isBalanceWarning(warning) && warning !== 'Modifica manuale: verifica disponibilità e incompatibilità'), ...rating.warnings, 'Modifica manuale: verifica disponibilità e incompatibilità'] } : item) }));
  };
  const replace = (match: Match, index: number, playerId: string) => changePlayers(match, match.players.map((id, i) => i === index ? playerId : id) as Match['players']);
  const swap = (match: Match, source: number, target: number) => changePlayers(match, match.players.map((id, index) => index === source ? match.players[target] : index === target ? match.players[source] : id) as Match['players']);
  return <><header><div><h1>Calendario</h1><p>Bloccate e disputate restano identiche. Trascina le posizioni o modificale manualmente.</p></div><div className="actions"><button className="secondary" disabled={!tournament.previousMatches} onClick={() => update(t => t.previousMatches ? { ...t, matches: t.previousMatches, previousMatches: undefined } : t)}><Undo2 size={17} /> Annulla rigenerazione</button><button onClick={regenerate}><Shuffle size={17} /> Genera / rigenera</button></div></header>{!tournament.players.length && <section className="notice">Aggiungi almeno quattro giocatori per generare il calendario.</section>}<div className="schedule">{tournament.matches.map(match => {
    const rating = calculateMatchBalance(match, tournament.players);
    return <div className={`match ${match.violations.length || rating.warnings.length ? 'has-warning' : ''}`} key={match.id}><div className="time">{match.start}<small>{match.end}</small></div><div className="match-content"><div className="teams"><span>{names.get(match.players[0])} + {names.get(match.players[1])}</span><b>VS</b><span>{names.get(match.players[2])} + {names.get(match.players[3])}</span></div><details className="balance-details"><summary><span className={`balance-badge balance-${rating.label}`} role="status" aria-label={`Rating equilibrio partita: ${rating.score} su 100, ${MATCH_BALANCE_LABELS[rating.label]}.`}>{rating.score}/100 · {MATCH_BALANCE_LABELS[rating.label]}</span></summary><div className="balance-detail"><p>{rating.explanation}</p><p>Forza coppia A: <b>{rating.teamAStrength}</b> · Forza coppia B: <b>{rating.teamBStrength}</b> · Differenza: <b>{rating.strengthDifference}</b></p><p>Equilibrio interno coppia A: <b>{rating.teamAInternalDifference <= 1 ? 'buono' : 'eterogeneo'}</b> · Coppia B: <b>{rating.teamBInternalDifference <= 1 ? 'buono' : 'eterogeneo'}</b></p>{rating.warnings.map(warning => <p className="balance-warning" key={warning}>{warning}</p>)}</div></details><details><summary>Modifica le 4 posizioni</summary><div className="positions">{match.players.map((id, index) => <div className="draggable-position" draggable key={`${match.id}-${index}`} onDragStart={() => setDragged({ matchId: match.id, position: index })} onDragOver={event => event.preventDefault()} onDrop={() => { if (dragged?.matchId === match.id && dragged.position !== index) swap(match, dragged.position, index); setDragged(undefined); }}><select value={id} onChange={e => replace(match, index, e.target.value)}>{tournament.players.map(player => <option key={player.id} value={player.id}>{fullName(player)}</option>)}</select></div>)}</div></details>{match.violations.filter(warning => !isBalanceWarning(warning)).map((violation, i) => <em key={i}>{violation}</em>)}</div><button className="icon" title="Blocca partita" onClick={() => update(t => ({ ...t, matches: t.matches.map(item => item.id === match.id ? { ...item, locked: !item.locked } : item) }))}>{match.locked || match.result?.outcome ? <Lock /> : <Unlock />}</button></div>;
  })}</div></>;
}
