import { useEffect, useMemo, useRef, useState } from 'react';
import { Copy, Download, ExternalLink, Link2, Mail, Send, Share2, X } from 'lucide-react';
import { Tournament } from '../models';
import { MAILTO_WARNING_LENGTH, TELEGRAM_SHARE_TEXT_WARNING_LENGTH, ShareScheduleOptions, buildMailtoUrl, buildTelegramShareUrl, copyScheduleToClipboard, defaultShareScheduleOptions, formatTournamentScheduleForSharing, shareWithWebShareApi, validRecipients } from '../services/scheduleSharing';

type Props = { tournament: Tournament; open: boolean; onClose: () => void; onDownloadPdf: () => void; onGeneratePublicLink: () => Promise<string> };
const publicUrl = () => (location.protocol.startsWith('http') && !['localhost', '127.0.0.1'].includes(location.hostname) ? location.href : undefined);

export function ShareScheduleDialog({ tournament, open, onClose, onDownloadPdf, onGeneratePublicLink }: Props) {
  const [options, setOptions] = useState<ShareScheduleOptions>(defaultShareScheduleOptions); const [message, setMessage] = useState(''); const [recipients, setRecipients] = useState(''); const [status, setStatus] = useState(''); const [publicLink, setPublicLink] = useState(''); const [linkBusy, setLinkBusy] = useState(false); const closeButton = useRef<HTMLButtonElement>(null);
  const generatedMessage = useMemo(() => formatTournamentScheduleForSharing(tournament, tournament.players, options), [tournament, options]);
  const incomplete = tournament.matches.filter(match => match.players.filter(id => tournament.players.some(player => player.id === id)).length < 4).length;
  useEffect(() => { if (open) { setMessage(generatedMessage); setStatus(''); setPublicLink(''); closeButton.current?.focus(); } }, [open, generatedMessage]);
  useEffect(() => { if (!open) return undefined; const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; window.addEventListener('keydown', onKeyDown); return () => window.removeEventListener('keydown', onKeyDown); }, [open, onClose]);
  if (!open) return null;
  const tooLongTelegram = message.length > TELEGRAM_SHARE_TEXT_WARNING_LENGTH; const tooLongEmail = message.length > MAILTO_WARNING_LENGTH;
  const toggle = (key: keyof ShareScheduleOptions) => setOptions(current => ({ ...current, [key]: !current[key] }));
  const sendTelegram = () => { if (tooLongTelegram && !window.confirm('Il calendario è troppo lungo per Telegram. Puoi copiare il testo o inviare il PDF. Vuoi tentare comunque?')) return; const popup = window.open(buildTelegramShareUrl(message, publicUrl()), '_blank', 'noopener,noreferrer'); if (!popup) setStatus('Popup Telegram bloccato: copia il testo o abilita i popup.'); };
  const sendEmail = () => { if (!validRecipients(recipients)) { setStatus('Inserisci indirizzi email validi, separati da virgole.'); return; } if (tooLongEmail && !window.confirm('Il contenuto potrebbe essere troppo lungo per il client email. Ti consigliamo il PDF. Vuoi tentare comunque?')) return; location.href = buildMailtoUrl(tournament, message, recipients); };
  const copy = async () => { try { await copyScheduleToClipboard(message); setStatus('Calendario copiato negli appunti.'); } catch { setStatus('Non è stato possibile copiare automaticamente il calendario. Seleziona il testo e copialo manualmente.'); } };
  const share = async () => { try { const shared = await shareWithWebShareApi(tournament, message, publicUrl()); if (!shared) setStatus('La condivisione diretta non è disponibile in questo browser.'); } catch { /* cancellation is non-blocking */ } };
  const generatePublicLink = async () => {
    setLinkBusy(true); setStatus('');
    try {
      const link = await onGeneratePublicLink(); setPublicLink(link);
      try { await copyScheduleToClipboard(link); setStatus('Link pubblico copiato negli appunti.'); }
      catch { setStatus('Link pubblico generato. Selezionalo qui sotto per copiarlo manualmente.'); }
    } catch (error) { setStatus(error instanceof Error ? error.message : 'Non è stato possibile pubblicare il calendario.'); }
    finally { setLinkBusy(false); }
  };
  const copyPublicLink = async () => { try { await copyScheduleToClipboard(publicLink); setStatus('Link pubblico copiato negli appunti.'); } catch { setStatus('Copia automatica non disponibile: seleziona il link e copialo manualmente.'); } };
  return <div className="share-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><div className="share-dialog" role="dialog" aria-modal="true" aria-labelledby="share-title">
    <header><div><h2 id="share-title">Condividi calendario</h2><p>{tournament.matches.length} partite · {message.length} caratteri</p></div><button ref={closeButton} className="icon secondary" aria-label="Chiudi finestra condivisione" onClick={onClose}><X /></button></header>
    {tournament.matches.length > 0 && <section className="public-link-panel"><div><h3>Calendario pubblico</h3><p>Pubblica una pagina in sola lettura, accessibile senza login.</p></div><button onClick={() => void generatePublicLink()} disabled={linkBusy}><Link2 size={17} /> {linkBusy ? 'Pubblicazione…' : tournament.isPublic ? 'Copia link pubblico' : 'Genera link pubblico'}</button>{publicLink && <div className="public-link-result"><input aria-label="Link pubblico del calendario" readOnly value={publicLink} onFocus={event => event.currentTarget.select()} /><button className="icon secondary" aria-label="Copia link pubblico" title="Copia link" onClick={() => void copyPublicLink()}><Copy size={17} /></button><a className="button secondary" href={publicLink} target="_blank" rel="noreferrer"><ExternalLink size={17} /> Apri</a></div>}</section>}
    <div className="share-body">{!tournament.matches.length ? <section className="notice">Non è ancora disponibile un calendario da condividere. Genera prima il calendario del torneo.</section> : <><div className="share-options"><label><input type="checkbox" checked={Boolean(options.includeLevels)} onChange={() => toggle('includeLevels')} /> Includi livelli</label><label><input type="checkbox" checked={Boolean(options.includeBalanceRating)} onChange={() => toggle('includeBalanceRating')} /> Includi rating equilibrio</label><label><input type="checkbox" checked={Boolean(options.includeResults)} onChange={() => toggle('includeResults')} /> Includi risultati</label><label><input type="checkbox" checked={Boolean(options.includeNotes)} onChange={() => toggle('includeNotes')} /> Includi note pubbliche</label><label><input type="checkbox" checked={Boolean(options.includePauses)} onChange={() => toggle('includePauses')} /> Includi pause</label><label><input type="checkbox" checked={Boolean(options.compact)} onChange={() => toggle('compact')} /> Formato compatto</label></div>{(tooLongTelegram || tooLongEmail || incomplete > 0) && <div className="share-warnings">{tooLongTelegram && <p>Il calendario è troppo lungo per Telegram: prova il formato compatto, il PDF o la copia del testo.</p>}{tooLongEmail && <p>Il contenuto potrebbe essere troppo lungo per il client email: consigliato il PDF.</p>}{incomplete > 0 && <p>Il calendario contiene {incomplete} partit{incomplete === 1 ? 'a incompleta' : 'e incomplete'}.</p>}</div>}<label className="share-preview">Anteprima modificabile<textarea value={message} onChange={event => setMessage(event.target.value)} /></label><label className="share-recipients">Destinatari email (facoltativi)<input value={recipients} placeholder="mario@example.com, anna@example.com" onChange={event => setRecipients(event.target.value)} /></label></>}{status && <p className="share-status" role="status">{status}</p>}</div>
    {tournament.matches.length > 0 && <div className="share-actions"><button onClick={sendTelegram}><Send size={16} /> Telegram</button><button onClick={sendEmail}><Mail size={16} /> Email</button><button className="secondary" onClick={copy}><Copy size={16} /> Copia</button><button className="secondary" onClick={onDownloadPdf}><Download size={16} /> PDF</button>{'share' in navigator && <button className="secondary" onClick={share}><Share2 size={16} /> Condividi</button>}</div>}
  </div></div>;
}
