create extension if not exists pgcrypto;

create table public.tournaments (
  id uuid primary key default gen_random_uuid(), name text not null, public_title text not null default '', tournament_date date,
  start_time time not null, end_time time not null, match_duration_minutes integer not null default 12 check (match_duration_minutes > 0), transition_duration_minutes integer not null default 3 check (transition_duration_minutes >= 0),
  max_games_per_match integer not null default 6 check (max_games_per_match > 0), scoring_mode text not null default 'golden_point' check (scoring_mode in ('golden_point','advantages')),
  victory_points integer not null default 3, draw_points integer not null default 1, defeat_points integer not null default 0, status text not null default 'draft' check (status in ('draft','scheduled','in_progress','completed','cancelled')),
  public_slug text not null unique, notes text, version bigint not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check (end_time > start_time)
);
create table public.players (
  id uuid primary key default gen_random_uuid(), tournament_id uuid not null references public.tournaments(id) on delete cascade,
  first_name text not null, last_name text not null default '', level text not null check (level in ('beginner','intermediate','advanced')), gender text not null check (gender in ('male','female','other')),
  notes text, status text not null default 'active' check (status in ('active','late','absent','injured','withdrawn')), sort_order integer not null default 0, version bigint not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.player_availability (id uuid primary key default gen_random_uuid(), player_id uuid not null references public.players(id) on delete cascade, available_from timestamptz not null, available_until timestamptz not null, created_at timestamptz not null default now(), check (available_until > available_from));
create table public.player_constraints (id uuid primary key default gen_random_uuid(), tournament_id uuid not null references public.tournaments(id) on delete cascade, player_a_id uuid not null references public.players(id) on delete cascade, player_b_id uuid not null references public.players(id) on delete cascade, constraint_type text not null default 'cannot_be_teammates' check (constraint_type = 'cannot_be_teammates'), created_at timestamptz not null default now(), check (player_a_id <> player_b_id));
create unique index player_constraints_unique_pair on public.player_constraints(tournament_id, least(player_a_id, player_b_id), greatest(player_a_id, player_b_id), constraint_type);
create table public.tournament_breaks (id uuid primary key default gen_random_uuid(), tournament_id uuid not null references public.tournaments(id) on delete cascade, title text not null default 'Pausa', starts_at timestamptz not null, ends_at timestamptz not null, created_at timestamptz not null default now(), check (ends_at > starts_at));
create table public.matches (
  id uuid primary key default gen_random_uuid(), tournament_id uuid not null references public.tournaments(id) on delete cascade, sequence_number integer not null, starts_at timestamptz not null, ends_at timestamptz not null,
  team_a_player_1_id uuid references public.players(id), team_a_player_2_id uuid references public.players(id), team_b_player_1_id uuid references public.players(id), team_b_player_2_id uuid references public.players(id),
  team_a_games integer, team_b_games integer, live_team_a_points text not null default '0' check (live_team_a_points in ('0','15','30','40','advantage')), live_team_b_points text not null default '0' check (live_team_b_points in ('0','15','30','40','advantage')),
  status text not null default 'scheduled' check (status in ('scheduled','in_progress','paused','time_expired','completed','cancelled')), is_locked boolean not null default false,
  balance_score integer check (balance_score between 0 and 100), balance_label text, timer_status text not null default 'idle' check (timer_status in ('idle','running','paused','expired','completed')),
  timer_duration_ms bigint, timer_remaining_ms bigint, timer_started_at timestamptz, timer_ends_at timestamptz, serving_team text check (serving_team in ('team_a','team_b') or serving_team is null), completed_at timestamptz,
  version bigint not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(tournament_id, sequence_number), check (ends_at > starts_at), check (team_a_games >= 0 or team_a_games is null), check (team_b_games >= 0 or team_b_games is null)
);
create table public.match_score_actions (id uuid primary key default gen_random_uuid(), match_id uuid not null references public.matches(id) on delete cascade, client_action_id uuid unique, action_type text not null, previous_score jsonb not null, next_score jsonb not null, created_at timestamptz not null default now());

create index players_tournament_id_idx on public.players(tournament_id); create index matches_tournament_id_starts_at_idx on public.matches(tournament_id, starts_at); create index availability_player_id_idx on public.player_availability(player_id); create index constraints_tournament_id_idx on public.player_constraints(tournament_id); create index breaks_tournament_id_starts_at_idx on public.tournament_breaks(tournament_id, starts_at); create index score_actions_match_id_created_at_idx on public.match_score_actions(match_id, created_at desc);

create or replace function public.set_updated_at_and_version() returns trigger language plpgsql as $$ begin new.updated_at = now(); new.version = old.version + 1; return new; end; $$;
create trigger tournaments_version before update on public.tournaments for each row execute function public.set_updated_at_and_version();
create trigger players_version before update on public.players for each row execute function public.set_updated_at_and_version();
create trigger matches_version before update on public.matches for each row execute function public.set_updated_at_and_version();

create or replace function public.replace_tournament_schedule(p_tournament_id uuid, p_expected_version bigint, p_matches jsonb) returns void language plpgsql security definer set search_path = public as $$
declare v_version bigint; begin select version into v_version from tournaments where id = p_tournament_id for update; if v_version is null then raise exception 'Tournament not found'; end if; if v_version <> p_expected_version then raise exception 'VERSION_CONFLICT'; end if; delete from matches where tournament_id = p_tournament_id and is_locked = false; insert into matches(tournament_id,sequence_number,starts_at,ends_at,team_a_player_1_id,team_a_player_2_id,team_b_player_1_id,team_b_player_2_id,is_locked,status) select p_tournament_id,(x->>'sequence_number')::int,(x->>'starts_at')::timestamptz,(x->>'ends_at')::timestamptz,nullif(x->>'team_a_player_1_id','')::uuid,nullif(x->>'team_a_player_2_id','')::uuid,nullif(x->>'team_b_player_1_id','')::uuid,nullif(x->>'team_b_player_2_id','')::uuid,coalesce((x->>'is_locked')::boolean,false),coalesce(x->>'status','scheduled') from jsonb_array_elements(p_matches) x; update tournaments set updated_at = now() where id = p_tournament_id; end; $$;

create or replace function public.import_tournament_snapshot(p_snapshot jsonb) returns uuid language plpgsql security definer set search_path = public as $$ declare v_id uuid := gen_random_uuid(); begin insert into tournaments(id,name,public_title,tournament_date,start_time,end_time,match_duration_minutes,transition_duration_minutes,max_games_per_match,scoring_mode,public_slug) values(v_id,coalesce(p_snapshot->>'name','Torneo importato'),coalesce(p_snapshot->'settings'->>'title',''),(p_snapshot->'settings'->>'date')::date,(p_snapshot->'settings'->>'start')::time,(p_snapshot->'settings'->>'end')::time,coalesce((p_snapshot->'settings'->>'playMinutes')::int,12),coalesce((p_snapshot->'settings'->>'warmupMinutes')::int,3),6,'golden_point',concat('import-',replace(v_id::text,'-',''))); return v_id; end; $$;

create view public.public_tournaments with (security_invoker = true) as select id,name,public_title,tournament_date,start_time,end_time,match_duration_minutes,transition_duration_minutes,max_games_per_match,status,public_slug,updated_at from public.tournaments;
create view public.tournament_standings with (security_invoker = true) as select p.tournament_id,p.id player_id,p.first_name,p.last_name,count(m.id) filter(where m.status='completed') played,count(m.id) filter(where m.status='completed' and ((m.team_a_player_1_id=p.id or m.team_a_player_2_id=p.id) and m.team_a_games>m.team_b_games) or ((m.team_b_player_1_id=p.id or m.team_b_player_2_id=p.id) and m.team_b_games>m.team_a_games)) wins,count(m.id) filter(where m.status='completed' and m.team_a_games=m.team_b_games) draws,count(m.id) filter(where m.status='completed') - count(m.id) filter(where m.status='completed' and m.team_a_games=m.team_b_games) - count(m.id) filter(where m.status='completed' and ((m.team_a_player_1_id=p.id or m.team_a_player_2_id=p.id) and m.team_a_games>m.team_b_games) or ((m.team_b_player_1_id=p.id or m.team_b_player_2_id=p.id) and m.team_b_games>m.team_a_games)) losses from players p left join matches m on m.tournament_id=p.tournament_id and p.id in (m.team_a_player_1_id,m.team_a_player_2_id,m.team_b_player_1_id,m.team_b_player_2_id) group by p.tournament_id,p.id,p.first_name,p.last_name;

alter table public.tournaments enable row level security; alter table public.players enable row level security; alter table public.player_availability enable row level security; alter table public.player_constraints enable row level security; alter table public.tournament_breaks enable row level security; alter table public.matches enable row level security; alter table public.match_score_actions enable row level security;
-- Prototype-only policies. Replace write policies with authenticated organizer policies before public deployment.
create policy "prototype public read" on public.tournaments for select using (true); create policy "prototype public write" on public.tournaments for all using (true) with check (true);
create policy "prototype public read" on public.players for select using (true); create policy "prototype public write" on public.players for all using (true) with check (true);
create policy "prototype public read" on public.player_availability for select using (true); create policy "prototype public write" on public.player_availability for all using (true) with check (true);
create policy "prototype public read" on public.player_constraints for select using (true); create policy "prototype public write" on public.player_constraints for all using (true) with check (true);
create policy "prototype public read" on public.tournament_breaks for select using (true); create policy "prototype public write" on public.tournament_breaks for all using (true) with check (true);
create policy "prototype public read" on public.matches for select using (true); create policy "prototype public write" on public.matches for all using (true) with check (true);
create policy "prototype public read" on public.match_score_actions for select using (true); create policy "prototype public write" on public.match_score_actions for all using (true) with check (true);
alter publication supabase_realtime add table public.tournaments, public.players, public.matches, public.tournament_breaks;
