import { FormEvent, ReactNode, useState } from 'react';
import { Eye, EyeOff } from 'lucide-react';
import { getSafeRedirect } from '../../auth/ProtectedRoute';
import { useAuth } from '../../auth/useAuth';

const emailIsValid = (email: string) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
const navigate = (path: string) => { window.history.replaceState(null, '', path); window.dispatchEvent(new PopStateEvent('popstate')); };
function AuthShell({ title, children }: { title: string; children: ReactNode }) { return <main className="auth-page"><section className="auth-card"><div className="auth-brand">🎾 <span>Baraonda<br />Padel</span></div><h1>{title}</h1>{children}</section></main>; }
function PasswordInput({ value, onChange, label = 'Password', autoComplete = 'current-password' }: { value: string; onChange: (value: string) => void; label?: string; autoComplete?: string }) { const [visible, setVisible] = useState(false); return <label>{label}<span className="password-field"><input type={visible ? 'text' : 'password'} value={value} onChange={event => onChange(event.target.value)} autoComplete={autoComplete} required /><button type="button" onClick={() => setVisible(!visible)} aria-label={visible ? 'Nascondi password' : 'Mostra password'} title={visible ? 'Nascondi password' : 'Mostra password'}>{visible ? <EyeOff size={17} /> : <Eye size={17} />}</button></span></label>; }

export function LoginPage() {
  const { signIn } = useAuth(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!email) return setError('Inserisci l’indirizzo email.'); if (!emailIsValid(email)) return setError('Inserisci un indirizzo email valido.'); if (!password) return setError('Inserisci la password.'); setError(null); setSubmitting(true); try { await signIn(email, password); const redirect = getSafeRedirect(new URLSearchParams(window.location.search).get('redirect')); navigate(redirect); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Non è stato possibile accedere.'); } finally { setSubmitting(false); } };
  return <AuthShell title="Accesso organizzatore"><form onSubmit={submit} noValidate><label>Email<input type="email" value={email} onChange={event => setEmail(event.target.value)} autoComplete="email" /></label><PasswordInput value={password} onChange={setPassword} /><p className="auth-error" role="alert">{error}</p><button className="auth-submit" disabled={submitting}>{submitting ? 'Accesso in corso…' : 'Accedi'}</button><button className="auth-link" type="button" onClick={() => navigate('/forgot-password')}>Password dimenticata?</button></form></AuthShell>;
}

export function ForgotPasswordPage() {
  const { sendPasswordReset } = useAuth(); const [email, setEmail] = useState(''); const [error, setError] = useState<string | null>(null); const [sent, setSent] = useState(false); const [submitting, setSubmitting] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!email) return setError('Inserisci l’indirizzo email.'); if (!emailIsValid(email)) return setError('Inserisci un indirizzo email valido.'); setError(null); setSubmitting(true); try { await sendPasswordReset(email); setSent(true); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Non è stato possibile inviare il link.'); } finally { setSubmitting(false); } };
  return <AuthShell title="Recupera password"><form onSubmit={submit} noValidate><label>Email<input type="email" value={email} onChange={event => setEmail(event.target.value)} autoComplete="email" /></label>{sent && <p className="auth-success">Se l’indirizzo è associato a un account, riceverai un’email con le istruzioni.</p>}<p className="auth-error" role="alert">{error}</p><button className="auth-submit" disabled={submitting}>{submitting ? 'Invio in corso…' : 'Invia link di recupero'}</button><button className="auth-link" type="button" onClick={() => navigate('/login')}>Torna all’accesso</button></form></AuthShell>;
}

export function ResetPasswordPage() {
  const { updatePassword, isAuthenticated } = useAuth(); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState(false); const [submitting, setSubmitting] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!password || !confirmation) return setError('Compila entrambi i campi password.'); if (password.length < 8) return setError('La nuova password deve contenere almeno 8 caratteri.'); if (password !== confirmation) return setError('Le password non coincidono.'); setError(null); setSubmitting(true); try { await updatePassword(password); setSuccess(true); window.setTimeout(() => navigate(isAuthenticated ? '/' : '/login'), 1000); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Non è stato possibile aggiornare la password.'); } finally { setSubmitting(false); } };
  return <AuthShell title="Imposta una nuova password"><form onSubmit={submit} noValidate><PasswordInput label="Nuova password" value={password} onChange={setPassword} autoComplete="new-password" /><PasswordInput label="Conferma nuova password" value={confirmation} onChange={setConfirmation} autoComplete="new-password" /><p className="auth-success">{success ? 'Password aggiornata correttamente.' : null}</p><p className="auth-error" role="alert">{error}</p><button className="auth-submit" disabled={submitting || success}>{submitting ? 'Aggiornamento…' : 'Aggiorna password'}</button></form></AuthShell>;
}
